name: Scrape data

on:
  push:
    branches:
      - ci*
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build scrapers
    runs-on: ubuntu-latest
    steps:
    - name: Print working directory
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        ls -al

    - name: Install Nix
      uses: cachix/install-nix-action@v7

    - name: Checkout scrapers repo
      uses: actions/checkout@v2
      with:
        repository: covid-db/covid-scrapers
        path: covid-scrapers

    - name: Print working directory
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        ls -al

    - name: Build scrapers
      working-directory: covid-scrapers
      run: 'nix-build -A haskell.covid-scrape --option substituters "https://zeus-ci.s3.amazonaws.com/ https://cache.nixos.org/" --option trusted-public-keys "ci.mightybyte.net-1:LXywRTa8NaNw7x32JJOncRMxFk2I36K6Tf6ac8VRnho= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="'

    - uses: actions/checkout@v2
      with:
        path: covid-db

    - name: Print working directory
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        ls -al

    - name: Run scrapers
      working-directory: covid-db/tables
      run: |
        pwd
        ls -al
        echo $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE/covid-scrapers
        ls -al $GITHUB_WORKSPACE/covid-scrapers/result
        ls -al $GITHUB_WORKSPACE/covid-scrapers/result/bin
        $GITHUB_WORKSPACE/covid-scrapers/result/bin/covid-scrape all
        git checkout -b scrape-`date +%Y-%m-%d`
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "Automated scraper commit"
    - name: Push scraped data
      uses: ad-m/github-push-action@master
      with:
        directory: covid-db
        github_token: ${{ secrets.GITHUB_TOKEN }}
